config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # devise_for :users

  root 'demarches#show'

  get 'demarches/main'
  get 'demarches/export'
  get 'demarches/export_all'
  get 'demarches/clear_checksums'
  get 'demarches/:demarche/with_discarded', to: 'demarches#with_discarded', as: 'demarches_with_discarded'

  get 'demarches(/:demarche)', to: 'demarches#show', as: 'demarches'

  get 'task_executions/:id/discard', to: 'task_executions#discard', as: 'discard'
  get 'task_executions/:id/undiscard', to: 'task_executions#undiscard', as: 'undiscard'
  get 'task_executions/search'
  put 'task_executions/:id/reprocess', to: 'task_executions#reprocess', as: 'reprocess'

  # view jobs
  match '/delayed_job' => DelayedJobWeb, :anchor => false, :via => %i[get post]

  # letter opener
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/views/shared/_reprocess.html.haml
- if current_user.is_admin
  %label.toggle-switch
    = check_box_tag :reprocess, '1', task_execution.reprocess, class: 'toggle-switch-checkbox', data: { remote: true, url: reprocess_path(task_execution), method: 'put' }
    %span.toggle-switch-control.round
    %span.toggle-switch-label.on A retraiter
    %span.toggle-switch-label.off Ne pas retraiter

app/views/shared/_tab_item.html.haml
%li.navitem
  - if notification
    %span.notifications{ 'aria-label': 'notifications' }
  = link_to(url, class: "nav-link#{active ? ' active' : ''}", 'aria-current': active ? 'page' : nil) do
    = label
    - if badge.present?
      %span.badge.badge-pill.badge-secondary= badge