config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # devise_for :users

  root 'demarches#show'

  get 'demarches/main'
  get 'demarches/export'
  get 'demarches/export_all'
  get 'demarches/clear_checksums'
  get 'demarches/:demarche/with_discarded', to: 'demarches#with_discarded', as: 'demarches_with_discarded'

  get 'demarches(/:demarche)', to: 'demarches#show', as: 'demarches'

  get 'task_executions/:id/discard', to: 'task_executions#discard', as: 'discard'
  get 'task_executions/:id/undiscard', to: 'task_executions#undiscard', as: 'undiscard'
  get 'task_executions/search'
  put 'task_executions/:id/reprocess', to: 'task_executions#reprocess', as: 'reprocess'

  # view jobs
  match '/delayed_job' => DelayedJobWeb, :anchor => false, :via => %i[get post]

  # letter opener
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/controllers/demarches_controller.rb
# frozen_string_literal: true

# controller to trigger CSV exports
#
class DemarchesController < ApplicationController
  before_action :authenticate_user!

  def export
    ExportJob.run(false)
    redirect_to demarches_path
  end

  def export_all
    ExportJob.run(true)
    redirect_to demarches_path
  end

  def clear_checksums
    Checksum.clear_all
    redirect_to demarches_path
  end

  def show
    @with_discarded = session[:with_discarded].present?
    @running = ExportJob.running?
    @demarches = demarche_list
    @demarche = current_demarche
    @dossiers = dossiers_for_current_demarche
  end

  def with_discarded
    if params[:with_discarded] == 'true'
      session[:with_discarded] = 'true'
    else
      session.delete(:with_discarded)
    end
    redirect_to demarches_path(params[:demarche])
  end

  private

  def current_demarche
    demarche_id = (params[:demarche].presence || session[:demarche])&.to_i
    if demarche_id.present? && @demarches.any? { |demarche, _count| demarche[0] == demarche_id }
      demarche = Demarche.find_by_id(demarche_id)
      if demarche.present?
        session[:demarche] = demarche.id.to_s
      else
        session.delete(:demarche)
      end
    end
    demarche || last_processed_demarche
  end

  def dossiers_for_current_demarche
    return [] unless @demarche.present?

    task_executions
      .order('task_executions.updated_at desc')
      .joins(job_task: { demarche: :instructeurs })
      .where(demarches_users: { user_id: current_user })
      .where(job_tasks: { demarche: @demarche })
      .where(id: Message.select(:task_execution_id))
      .includes(:messages)
      .includes(:job_task)
      .group_by(&:dossier)
  end

  def task_executions
    @with_discarded ? TaskExecution.discarded : TaskExecution.kept
  end

  def demarche_list
    task_executions
      .where(id: Message.select(:task_execution_id))
      .joins(job_task: { demarche: :instructeurs })
      .where(demarches_users: { user_id: current_user })
      .distinct
      .group('demarches.id', 'demarches.name')
      .count(:dossier)
  end

  def last_processed_demarche
    TaskExecution.order('task_executions.updated_at desc').joins(:messages).first&.job_task&.demarche
  end
end

app/views/demarches/show.html.haml
.container-fluid
  .row
    .col-10
      - if current_user.is_admin
        - if @running
          %p
            Synchronisation en cours. Rafraichir la page ulterieurement.
        - else
          = link_to 'Traiter les nouveaux dossiers', demarches_export_path, class: 'btn btn-primary'
          = link_to 'Traiter tous les dossiers', demarches_export_all_path, class: 'btn btn-secondary'
          = link_to 'Effacer les checksums', demarches_clear_checksums_path, class: 'btn btn-secondary'
    - if @demarche.present?
      .col.text-right
        - image = @with_discarded ? 'masquer.svg' : 'afficher.svg'
        = link_to image_tag(image, class: 'discard btn btn-light'), demarches_with_discarded_path(with_discarded: !@with_discarded, demarche: @demarche)
  .row
    %p
  .row
    .col
      %nav
        %ul.nav.nav-tabs
          - @demarches.each do |demarche, count|
            = tab_item(demarche[1],
                       demarches_path(demarche: demarche[0]),
                       active: demarche[0] == @demarche&.id,
                       badge: count)
  .row
    .col
      %h3
        = @dossiers.size
        dossiers
      %table.table.table-striped
        - @dossiers.each do |dossier_number, executions|
          %tr.d-flex
            %td
              - demarche_number = executions.first.job_task.demarche_id
              = link_to "Dossier #{dossier_number}", ENV.fetch('GRAPHQL_HOST') + "/procedures/#{demarche_number}/dossiers/#{dossier_number}", target: '_blank'
              %br
              Exporté le
              = executions.first.updated_at.strftime('%d/%m/%Y à %H:%M')
              -# = render partial: "shared/reprocess", locals: { task_execution: execution }
            %td.col-10
              - executions.first(50).each do |execution|
                - if execution.discarded?
                  = link_to image_tag('afficher.svg', class: 'discard btn btn-light'), undiscard_path(execution, discarded: @discarded)
                - else
                  = link_to image_tag('masquer.svg', class: 'discard btn btn-light'), discard_path(execution, discarded: @discarded)
                = execution.job_task.name
                = render partial: 'shared/reprocess', locals: { task_execution: execution }
                - messages = execution.messages.sort_by(&:level)
                %table.table
                  - messages.each do |message|
                    %tr.d-flex
                      %td.col-4.col-md-3
                      %td.col-2.col-md-1= message.level_string
                      %td.col-6.col-md-8= sanitize(message.message)