config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # devise_for :users

  root 'demarches#show'

  get 'demarches/main'
  get 'demarches/export'
  get 'demarches/export_all'
  get 'demarches/clear_checksums'
  get 'demarches/:demarche/with_discarded', to: 'demarches#with_discarded', as: 'demarches_with_discarded'

  get 'demarches(/:demarche)', to: 'demarches#show', as: 'demarches'

  get 'task_executions/:id/discard', to: 'task_executions#discard', as: 'discard'
  get 'task_executions/:id/undiscard', to: 'task_executions#undiscard', as: 'undiscard'
  get 'task_executions/search'
  put 'task_executions/:id/reprocess', to: 'task_executions#reprocess', as: 'reprocess'

  # view jobs
  match '/delayed_job' => DelayedJobWeb, :anchor => false, :via => %i[get post]

  # letter opener
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/views/layouts/_flash_messages.html.haml
#flash-messages
  - if flash.any?
    - flash.each do |type, msg|
      - tag = type == 'notice' ? 'info' : 'warning'
      %div{ class: "alert alert-#{tag}" }= msg

app/views/layouts/_header.html.haml
%nav.navbar
  %a.navbar-brand{ href: root_path }
    = image_tag 'sefidem.png', style: 'width: 90px'
    = SITE_NAME
  %ul.nav.text-right
    = render partial: 'layouts/search_dossiers_form'
    - if user_signed_in?
      %li.nav-item
        = link_to 'se déconnecter', destroy_user_session_path, method: :delete, class: 'navlink', style: 'margin-right: 15px'
      %li.nav-item
        = link_to 'mon profil', edit_user_registration_path, class: 'navlink'
    - else
      %li.nav-item
        = link_to 'connexion', new_user_session_path, class: 'navlink', style: 'margin-right: 15px'
      %li.nav-item
        = link_to 'créer un compte', new_user_registration_path, class: 'navlink'

app/views/layouts/_search_dossiers_form.html.haml
.header-search{ role: 'search' }
  = form_tag task_executions_search_path, method: :get, class: 'form' do
    = label_tag :q, 'Numéro de dossier', class: 'hidden'
    = text_field_tag 'q', local_assigns[:search_terms] ? search_terms : '', placeholder: 'Rechercher un dossier'
    %button{ title: 'Rechercher' }
      = image_tag 'search-blue.svg', alt: 'Rechercher', 'aria-hidden': 'true'

app/views/layouts/application.html.haml
%html{ lang: 'fr' }
  %head
    %meta{ 'http-equiv': 'Content-Type', content: 'text/html; charset=UTF-8' }
    %meta{ 'http-equiv': 'X-UA-Compatible', content: 'IE=edge' }
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1' }
    = csrf_meta_tag
    = csp_meta_tag

    %title
      = content_for?(:title) ? "#{yield(:title)} · #{SITE_NAME}" : SITE_NAME

    = favicon_link_tag(image_path('favicons/pf16x16.png'), type: 'image/png', sizes: '16x16')
    = favicon_link_tag(image_path('favicons/pf32x32.png'), type: 'image/png', sizes: '32x32')
    = favicon_link_tag(image_path('favicons/pf96x96.png'), type: 'image/png', sizes: '96x96')

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render partial: 'layouts/header'
    = render partial: 'layouts/flash_messages'
    .content
      = yield